DROP TABLE IF EXISTS SAMPLETABLE;	

CREATE TABLE SAMPLETABLE (
    ID INT PRIMARY KEY CLUSTERED,
	NAME nvarchar(200),
);

insert into SAMPLETABLE values (1, 'Temp Name');
insert into SAMPLETABLE values (2, 'Temp 2');